services: 
  # FastAPI Application 
  fastapi:
    container_name: fastapi
    ports:
     - "8000:8000"
    networks: 
      - backend
    restart: always
    env_file:
      - /env/.env.app

    depends_on:
      pgvector:
        condition: service_healthy


  # Nginx Servicve 


  # Postgress(PGVectore)
  pgvector:
    image: pgvector/pgvector:0.8.1-pg18
    container_name: pgvector
    ports:
     - "5432:5432"
    volumes:
      -"pgvector:/var/lib/postgresql/data"

    env_file:
      - ./env/.env.postgres

    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CHD-SHELL", "pg_isready - U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  # Qdrant(VectorDB)
  qdrant:
    image: qdrant/qdrant:v1
    container_name: qdrant 
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always



  # Prometheus Monitoring
  promthues:
    image : prom/prometheus:v3.7.1
    container_name: promethues
    ports: 
     - "9090:9090"
    volumes:
      - promethues_data:/promethues
      - ./promethues/promethues.yml:/etc/promethues/promethues.yml
    networks:
      - backend
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'  # âœ… Enables /-/reload 
    


  # Grafana Dashboard 
  grafana:
    image: grafana/grafana:12.3.0-18765596677
    container_name:  grafana
    ports: 
     - "3000:3000"
    volumes:
      - grafana_data:/var/lab/grafana
    env_file:
      - ./env/.env.grafana
    depends_on:
      - prometheus
    networks:
      - backend
    restart: always



  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:v1.10.1
    container_name: node-exporter
    ports: 
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
     - backend
    restart: always 




  # Postgres Exporter For  Postgress Metrics

  postgres-exporter:
    image: postgres-exporter bitnami/postgres-exporter:latest
    container_name:  postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - ./env/.env.postgres-exporter
    depends_on:
      - pgvector
    networks:
      - backend
    restart: always

